title: Using functions in dictionaries
hero_image: images/banner.png
description: python-advanced-dictionaries description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Functions in dictionaries
