title: Storing functions in Python dictionaries
hero_image: images/banner.png
description: Store and use functions in dictionaries
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
interests: ""
technologies: "python"
steps:
  - title: Store and use functions in dictionaries

